### ISSUE TITLE
improve on boarding + provide some pre-populated virtues

### ISSUE THREAD

**Issue by gwensmu** [gwensmu/daimon#3]
no one is getting "virtues have habits which are instantiated in practices" from the UI when no virtues/habits are populated -- everyone feels better when i show them an example. pre-populate new users with a sample virtue.

**Comment by oldwestaction** [comment]
i really like the [sample virtues page](https://shrouded-bayou-1718.herokuapp.com/static/samples). i think it would be cool if each sample virtue ("gratitude", "friendship", "self care") had a button so that i could choose to copy it over to my own virtues list.

i would also like it if you included your personal definitions of what constitutes a "virtue" vs. "habit" vs. "practice"!

**Comment by gwensmu** [comment]
closing this so i can break it up into parts.
