### ISSUE TITLE
i think it would be cool if there was a nav bar

### ISSUE THREAD

**Issue by oldwestaction** [gwensmu/daimon#4]
both so that it would be easier for me to access each part of the app, and also so that the hierarchy of pages/functions could be more clear to a new user.

i imagined something like: 

- home (what shows up at / -- could maybe be merged w/ "overview" screen?)
- overview (so like the screen that shows up at /users/n)
- virtues (maybe not clickable since you get this info from the overview page)
  - create a new virtue
  - [ virtue 1 ]
  - [ virtue 2 ]
  - [ virtue n ]
- stats
- view / edit account info
- log out

**Comment by oldwestaction** [comment]
oh and another nav/ux thing -- it's hard to tell what's clickable/a link until you mouseover and see the hover state. would suggest making the link styles distinct from the text styles and possibly making them more... buttony?

**Comment by gwensmu** [comment]
i added a side menu. thanks for your thoughts helped me to get out of "i don't have a viewpager and i feel stuck." closing this for now although, let me know if you have thoughts about the edit links for practices/habits/etc w/in a particular virtue - maybe virtue-specific top nav for virtue-specific interaction will make sense. 

I want to keep editing and deleting elements of the virtue on separate pages for right now because i think it makes it slightly less confusing.
